[project]
name = "benchflow"
version = "0.1.0"
description = "BenchFlow is a tool for easy benchmarking."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.6",
    "requests>=2.32.3",
    "ruff>=0.9.2",
    "uvicorn>=0.34.0",
]
